### ISSUE TITLE
add browsable data dictionary

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#13]
we have all the metadata on eg. the 2011 census which has been imported into the system, but no way for users to browse through that. add a browser (probably integrated with the layer editor) to let users discover attributes relevant to the current geometry and copy & paste them into an equation

**Comment by keithamoss** [comment]
Let's think about what the ideal experience is for accessing this information. I'd love to see some elegant auto-complete functionality, but let's discuss and make sure that's actually going to be good for users.

**Comment by keithamoss** [comment]
Further random thoughts:

1. What if the expression editor used the human-readable field names instead of, or as an alternative to, the field codes?

2. Have a set of pre-created expressions to choose from. E.g. "℅ of TypeofPerson per Whatever Your Geometry Is". If successful this could be a GUI layer on top of common expressions that just lets the user choose tables from dropdowns.

**Comment by keithamoss** [comment]
For a quick win on the expression input we could use a chip-input field to support richer expressions.

https://github.com/TeamWertarbyte/material-ui-chip-input

**Comment by keithamoss** [comment]
So there are a couple of challenges here:

- The Census has over 690,000 (!!) columns. SA3s alone have 69,000 columns. SA3s mentioning the word "Diploma" has 830 columns.
- The Census metadata is unstructured. We have long column names containing gender, age, date of Census, and a concept (e.g. Occupations, Education level, ...) that are all packaged up in the one string!

Until we get more non-Census data in I feel it's premature to go and structure the column and table metadata too much, so we'll stick to letting the user filter text.

**So, for the MVP what we'll do is** let the user apply simple text filters (*ILIKE '%string%'*) to the table and column names. These can be represented as chips by [material-ui-chip-input](https://github.com/TeamWertarbyte/material-ui-chip-input). Each term will form an *AND* filter with any other terms (i.e. Entering "Diploma" and "Advanced" would result in *ILIKE '%Diploma%' AND ILIKE '%Advanced%'*).

IF we were just doing Census then the alternative here would be to provide a more traditional Census navigator that drilled down from geometries to categories to tables to columns. That approach may still be valid (we have those concepts in geometry -> table -> column), but that can wait (MVP and all that).

**Comment by keithamoss** [comment]
# Approaches to exploring and visualising the available datasets

## Card-based Layout (#1)
![card-layout1](https://cloud.githubusercontent.com/assets/1672960/25321812/2dee642a-28e4-11e7-85c7-f57b1744ccd1.png)

https://gist.github.com/keithamoss/aeceb4f8743f20310b011f67354c7e2b


## Card-based Layout (#2)
![card-layout2](https://cloud.githubusercontent.com/assets/1672960/25321814/342222be-28e4-11e7-8156-350da36061e3.png)

https://gist.github.com/keithamoss/eef8dd63540bbf94d3293820ef5294f7
**Issues:** Lots of scrolling when there's more than a trivial number of results. The higher-level groupings (table, schema) aren't exposed until you expand the card.


## ListItem-based Layout
![list-layout](https://cloud.githubusercontent.com/assets/1672960/25321822/423edfc2-28e4-11e7-85d0-97f220688642.png)

https://gist.github.com/keithamoss/8a1dc48e4993d6b286a24556a5f0a55b
**Issues:** Lots of scrolling to do if you have more than a few results.


## Nested List Layout
![nested-list-layout](https://cloud.githubusercontent.com/assets/1672960/25321826/48311c9c-28e4-11e7-816e-fe224df8aef0.png)

https://gist.github.com/keithamoss/397ca222dd781b2e6edb0c6cd9737190
**Issues:** Lists are limited to two lines of secondary text and don't support RaisedButtons (only IconButtons).


## Table in a Dialog Layout
![dialog-table-layout](https://cloud.githubusercontent.com/assets/1672960/25321835/519b6eea-28e4-11e7-8880-996fdf3affb6.png)

https://gist.github.com/keithamoss/ab3b2e92ebf79dd18e1b826c2c31cd62
**Issues:** Columns fit to the width of the whole table, so long column names get truncated. No way to nest items or have TableRow groupings to nicely get around that. (We might be able to develop that ourselves, although.)

**Comment by keithamoss** [comment]
# Approaches considered but not explored

## Data Store
An interface presented to the user in response to choosing to create a new layer.

A near-fullscreen sized interface utilising smaller horizontally tiled cards for each column (dataset).

The top would have a filter to limit the results by schema, table, and keywords. An advanced filter mode could expand the filter component to show more advanced controls.

The "Data Store" interface may make it easier to expand to include other concepts in future, such as:

- **Pre-canned layers:** Where the user only chooses a geometry and dataset and we 'intelligently' pre-fill the rest of the information. (The user can still edit to tweak settings.)
- **Dataset themes:** A new categorisation of our own choosing that groups together datasets in a similar theme.
- **Highlighted datasets:** Highlighting datasets of our own choosing, that are popular, et cetera.

**Comment by keithamoss** [comment]
# Additional considerations

As a user I want to easily discover common fields (like total population, et cetera) to complement the data point I'm looking at.

e.g. I want to plot the % of households in an area with couples with no children (b4822). To do that I need to be able to easily find the total number of families (b4866) in that area.

Right now that takes quite a few clicks to achieve, and you need to know to look in the same table for the right "total" column.

**Comment by keithamoss** [comment]
MVP of the data dictionary browser taken care of by 909d74ba446f84a2d9e3a7f312368e6480683ba1.
