### ISSUE TITLE
Setup an ealgis.org email account and verify ealgis.org in Mailgun

### ISSUE THREAD

**Issue by keithamoss** [ealgis/ealgis#149]
We're using a sandbox domain tied to my personal email address in Mailgun at the moment. Its limited to sending to pre-authorised email addresses, so it won't work for PROD.

We need to:

- Setup a something@ealgis.org email account and update `EALGIS_SITE_CONTACT_EMAIL` in `web-variables.env`
- Use it to register for Mailgun and then follow [these steps](https://documentation.mailgun.com/en/latest/quickstart-sending.html#verify-your-domain) to verify ealgis.org as a domain we can send from
- Update `MAILGUN_DOMAIN`, `MAILGUN_API_KEY`, and `MAILGUN_FROM` in `web-variables.env`

**Comment by grahame** [comment]
Done.
