### ISSUE TITLE
set up django-rest-framework

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#22]
- [x] Setup Django REST Framework
- [x] Migrate data models from db.py
- [x] Identify legacy routes to migrate
- [x] Enumerates over the available schemas
- [x] Migrate routes from Flask
- [x] Decide how `TableInfoViewSet` is going to work. Just geometry tables or all tables? It does a bit of both right now (leftover from EAlGIS v1). (**Decision:** One endpoint for both spatial and non-spatial data now as that's closer to the database structure.)
- [x] Support `ealgis_metadata_table` and properly document how to get that into the SQL dump. (And add a `name` field to it for the UI to be able to refer to it?)
- [x] /tableinfo/{table} isn't decoding the description JSONField via the serializer
- [x] Run `makemigrations`

**To migrate:**
- [x] /users
- [x] /maps
- [x] /datainfo (Need to have some test data to play with to be able to port and test the code. /datainfo that exists should provide this once we have some test data - but @grahame added a bunch of caching smarts to `db.py` EALGIS.get_datainfo() in EALGIS1 that we may or may not need/want to port.)
- [x] /colours
- [x] POST/PUT /map/<map_name> (Need to wire up the SQL compilation. Depends on having data.)
- [x] Check logic re nullable fields

**Skipped:**
- /map/<map_name>/legend/<layer_id>/<client_rev> (*Reason:* We'll be doing legends differently.)
- /map/<map_name>/export-csv (*Reason:* Who would actually be using it in the MVP?)
- /map/<map_name>/export-csv/<ne>/<sw> (*Reason:* Who would actually be using it in the MVP?)
- /mapexists/<map_name> (*Reason:* Port it later if we end up needing it. API changes may remove the need.)
- /settings (*Reason:* NFI what's in here. In EALGIS1 it's just a generic settings container that doesn't appear to be used anywhere but the CLI, and then only exposed as an interface. Port it later if we need it.)

### API Documentation Thoughts
http://www.django-rest-framework.org/topics/documenting-your-api/ (Will it support @detail_ decorators and our weird hidden parameters in some fashion?) - Only do this if it's quick and basically free.

[Django REST Swagger](http://marcgibbons.github.io/django-rest-swagger/) looks promising, but lacked a way to show parameters from a combination of Django and SQLAlchemy models.

How do we expose the hidden query params like schema_name and only_spatial?

**Comment by keithamoss** [comment]
See 7b2ce6c for initial models.

**Comment by keithamoss** [comment]
[Nullable fields in Django models](http://stackoverflow.com/a/16046497)

**Comment by keithamoss** [comment]
Re nullable fields - 

In EALGIS1 most columns are set to SQLAlchemy's nullable=False (default True).

From SQLAlchemy docs:

```
nullable – If set to the default of True, indicates the column will be rendered as allowing NULL, else it’s rendered as NOT NULL. This parameter is only used when issuing CREATE TABLE statements.
```

In EALGIS2 I've left us at Django's default of null = False for all bar the two `JSONFields`.

Quoth [Django's docs](https://docs.djangoproject.com/en/1.10/ref/models/fields/#null) on the matter -

```
Avoid using null on string-based fields such as CharField and TextField because empty string values will always be stored as empty strings, not as NULL. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL.
```

**Comment by keithamoss** [comment]
@grahame I've ported over all of the API endpoints that I can without having a database populated with at least a few dummy datasets. The two main endpoints that need porting and testing once that happens are `GET /datainfo` and `POST/PUT /map`.

To get some dummy data in we're going to need to spend some time porting `aus_census_2011.py` and the rest of the data loaders over and wire them up to Django.

Let's chat about how we can best approach that, and if there's a better way that means we won't be throwing work away once the data loaders get broken out into a separate project.

**Comment by keithamoss** [comment]
Discussion re data loading -

Port the Census data loader to its own Docker container in a separate project and have it generate an SQL dump / run SQL directly against a PostgreSQL/PostGIS database. Have the data loader(s) and EALGIS agree on an approach to tables, metadata, and schemas. EALGIS on boot up can then go through and scan metadata tables in all of the PostgreSQL schemas it can see looking for valid data sources.

Longer-term it should be a separate project decoupled from EALGIS anyway, so we may as well start that process now.

The upside to this approach is in making our EALGIS Docker container lighter (no GIS crap floating around that's just used for data loads) and it's more extensible - e.g. Loading in GNAF would essentially be a matter of grabbing @minus34's SQL dump, loading it, and writing a metadata table for it and - **BAM!** - EALGIS knows about GNAF.

**Comment by keithamoss** [comment]
[Use SQLAlchemy with Django](http://rodic.fr/blog/sqlalchemy-django/)
[Integration SQLAlchemy in Django projects for effective query building purposes](https://github.com/Deepwalker/aldjemy)

[How to use schemas in Django?](http://stackoverflow.com/questions/1160598/how-to-use-schemas-in-django)

**Comment by keithamoss** [comment]
- [ ] http://www.django-rest-framework.org/topics/documenting-your-api/ (Will it support @detail_ decorators?
- [ ] Run `makemigrations`

**Comment by keithamoss** [comment]
All done! :)
