### ISSUE TITLE
port Maps model into Django, expose via API

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#23]

**Comment by keithamoss** [comment]
Ported in #22, but requires dummy data to port over and test the SQL generation code. Blocked by #22.

**Comment by keithamoss** [comment]
**Some notes from investigating how to hook-up the SQL compilation code.**

Overwriting `create`, `update,` et al. on ModelViewSets looks like this.

```python
def update(self, request, pk=None, format=None):
    return("update")
    queryset = self.get_queryset()
    map = queryset.filter(id=pk).first()
    map.set(map.json)
    map.save()

    return Response(map)
```

Using Signals to run code post-create or post-update looks like this.

```python
from django.dispatch import receiver

@receiver(models.signals.post_save, sender=MapDefinition)
def map_definition_post_save(sender, instance, created, *args, **kwargs):
    print(sender)
    if created:
        rev = instance.set(instance.json)
        instance.save()
```

**Comment by keithamoss** [comment]
There's some slight hackiness in this latest commit re [django/ealgis/models.py](https://github.com/ealgis/ealgis/commit/0f5b375bb6e1e1311796cc7f799725f054eab4b3#diff-d1a23534b8a89ba964d911977d01f469) and [django/ealgis/ealgis.py](https://github.com/ealgis/ealgis/commit/0f5b375bb6e1e1311796cc7f799725f054eab4b3#diff-d1a23534b8a89ba964d911977d01f469) that should be fixed up later.

As far as I can tell, Flask SQL Alchemy gave us some nice stuff that made relations between tables work much more nicely (e.g. Being able to call `self.reprojections.all()` on `GeometrySource` to return all related rows from the `GeometrySourceProjected` model.) Now that we've dropped Flask SQL Alchemy things are...less nice.

According to [Working with Related Objects](http://docs.sqlalchemy.org/en/latest/orm/tutorial.html#working-with-related-objects) and [Linking Relationships with Backref](http://docs.sqlalchemy.org/en/latest/orm/backref.html) this sort of thing should still be possible. But I can't get it to work with our setup, and this is only an MVP.

Will farm this out to an enhancement ticket before closing.

**Comment by keithamoss** [comment]
OK, so there are still a few little fruity details about how we're using SQLAlchemy's automapping magic. I've filed those in #43.
