### ISSUE TITLE
set up geoserver

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#24]
- [x] Bring GeoServer Docker container across from the `ealgis/geoserver` branch
- [x] Define approach to GeoServer first run init and config
- [x] Set a sane productiony GeoServer config on container startup
  - [Proxy base url and logging profile](http://docs.geoserver.org/2.7.0/user/webadmin/server/globalsettings.html#proxy-base-url)
  - [Require files to exist](http://docs.geoserver.org/stable/en/user/datadirectory/setting.html#require-files-to-exist)
  - [Production config](http://geoserver.geo-solutions.it/edu/en/adv_gsconfig/gsproduction.html)
  - [Passwords](http://docs.geoserver.org/latest/en/user/security/passwd.html)
  - [FeatureType cache size](http://docs.geoserver.org/2.7.0/user/webadmin/server/globalsettings.html#feature-type-cache-size)
  - [Running in a production environment](http://docs.geoserver.org/stable/en/user/production/)
- [x] Punch a hole to GeoServer through the web container
- [x] Define how we'll handle accessing/securing the GeoServer admin web interface (We'll set a good strong password for now)
- [x] Refer to best practice for running [kartoza/docker-geoserver](https://github.com/kartoza/docker-geoserver#storing-data-on-the-host-rather-than-the-container) (Data on host/in a data volume; Setting Tomcat props)
- [x] Identify and cleanup issues logged during GeoServer startup

Blocks #44.

**Comment by keithamoss** [comment]
**GeoServer Setup**

- Changed `admin` account password to `31Wq:^]$eOw{/k,gTf%9qa/c`. /data/security/usergroup/default/users.xml.
- Enabled `Encrypting web UI URLs` and set password encryption to `Strong PBE`. /data/security/config.xml.
- Set the `Default XML user/group service` password encryption to `Digest`. /data/security/usergroup/default/config.xml

**Comment by keithamoss** [comment]
Community modules are found here: http://ares.opengeo.org/geoserver/2.9.x/community-latest/
