### ISSUE TITLE
Resolve watchify via gulp not picking up all changes when run in Docker

### ISSUE THREAD

**Issue by keithamoss** [ealgis/ealgis#31]
It only works locally on macOS at the moment. When run in a Docker container it only works for index.

There may be clues here: http://stackoverflow.com/a/33907187

**Comment by grahame** [comment]
It works when index.tsx is changed, but not when any of the dependencies are changed (eg. files in `components/`)

**Comment by keithamoss** [comment]
@grahame This blog post talks about how to run Webpack without the need for manually including livereload.js as a <script> tag.

https://www.jonathan-petitcolas.com/2015/05/15/howto-setup-webpack-on-es6-react-application-with-sass.html

**Comment by grahame** [comment]
I want to do the serving through Django's runserver, so that example
doesn't really work :-)

**Comment by grahame** [comment]
cool, done :-)
