### ISSUE TITLE
Experiment with the new ST_AsMVT() function in PostGIS master

### ISSUE THREAD

**Issue by keithamoss** [ealgis/ealgis#55]
Björn Harrtell of Carto [has just pushed](https://github.com/postgis/postgis/commit/fee914f1174c1ab6869fbc9e23634fcd68a8455c) `ST_AsMVT()` into PostGIS master for release in 2.4.

# Research and links (2018)
- [Carto Blog: MVT generation: Mapnik vs PostGIS](https://carto.com/blog/inside/MVT-mapnik-vs-postgis/)
- [Carto Blog: PostGIS Performance Profiling](https://carto.com/blog/inside/postgis-performance/)
- [Restyle feature when overzooming OpenLayers 4](https://stackoverflow.com/questions/48382603/restyle-feature-when-overzooming-openlayers-4)
- [Line Simplification Demo: Douglas–Peucker vs Visvalingam](https://bost.ocks.org/mike/simplify/)
- [Why Simplification Is Complicated](https://www.spheraware.com/blog/post/why-simplification-complicated)
- [postgis-vt-util GitHub: postgres helper functions for making vector tiles](https://github.com/mapbox/postgis-vt-util)
- [Vector tiles, PostGIS and OpenLayers](https://medium.com/tantotanto/vector-tiles-postgis-and-openlayers-258a3b0ce4b6)
- [How to make mvt with PostGIS](https://blog.jawg.io/how-to-make-mvt-with-postgis/)

# Initial musings (2017)
If this works as advertised it as the potential to allow us to remove our (relatively heavy) GeoServer component and replace it with a lightweight layer in Django, that speaks directly to PostGIS, and returns MapBox Vector Tiles to the client.

The backend will need to present an interface to OpenLayers that looks like a tiled map service (i.e. a URL with X, Y, and Z coordinates), and before sending those to PostGIS will need to convert it to a bounding box representing the tile being requested.

If all goes to plan consideration will need to be given to:

- Whether the backend returns one layer per tile or multiple layers squashed into one tile
- How we go about doing on-the-fly feature generalisation (simplification)
- Setting the appropriate cache headers and constructing a URL with a hash that is globally unique across all permeations of EALGIS layers
- Whether we need a backend caching layer (ideally, something in memory like memcached or Redis)

Björn published [a Docker image](https://gist.github.com/bjornharrtell/502353b063249880e15b1f66e2db91c6) back in November 2016 that we could use to evaluate this approach. Failing that, we can just build PostGIS master.

The original OSGeo email chain where Bjorn posted his work is here: http://osgeo-org.1560.x6.nabble.com/Native-MVT-output-support-in-PostGIS-td5287310.html

**An alternative approach using node-mapnik**
[PostGIS to Protobuf (with vector tiles)](http://frankrowe.org/posts/2015/03/17/postgis-to-protobuf.html)
[PostGIS to Vector Tiles (with OpenLayers)](http://frankrowe.org/posts/2016/05/05/postgistovector.html)

**An alternative alternative approach**
https://github.com/tilezen/mapbox-vector-tile
https://gist.github.com/tucotuco/1193577

**Comment by grahame** [comment]
Have a build of postgis running in a docker container to get a hang for building it. I plan to build a docker container which makes a .deb from whatever is in postgis master at the time you run it, and spits it out to a known volume. We can then install that into a fork of the mdillon/postgis container.

**Comment by grahame** [comment]
OK, so the `mdillon/postgis` container is based on too old a base container for things to be happy.

```
postgres@04acfdd486cf:/postgis$ pkg-config --exists --print-errors 'libprotobuf-c >= 1.1.0'
Requested 'libprotobuf-c >= 1.1.0' but version of libprotobuf-c is 1.0.2
```

Looks like I'll have to rebuild on top of `debian:sid` to get GDAL 3.5 and new enough versions of protobuf for the vector tile support to compile.

**Comment by keithamoss** [comment]
c.f. https://github.com/ealgis/ealgis/wiki/Vector-Tiles-Research

**Comment by keithamoss** [comment]
https://github.com/shongololo/postgis is a good lead on a PG2.4-Dev container. It seems to just need Protobuf installed before we compile PostGIS.

**Comment by keithamoss** [comment]
On building PostGIS with protobuf support:

- https://postgis.net/docs/manual-dev/postgis_installation.html
- Lots of useful comments in [this issue tracker thread](https://trac.osgeo.org/postgis/ticket/3661)
- https://github.com/protobuf-c/protobuf-c
- https://hub.docker.com/r/shongololo/postgis/ (latest PostGIS Docker container, but no protobuf)

**Comment by keithamoss** [comment]
```
apt-get update
apt-get install libgeos-dev
pip install shapely
pip install mapbox-vector-tile
```

https://github.com/mapbox/geojson-vt
https://github.com/Stezii/tilestrata-postgismvt
https://github.com/pka/t-rex/

**Comment by keithamoss** [comment]
Extract EALGIS core tables:
```
pg_dump --username=postgres --dbname=postgres --exclude-schema=aus_census_2011 --exclude-schema=tiger --exclude-schema=tiger_data --exclude-schema=topology --exclude-schema=pg_catalog --exclude-schema=information_schema --exclude-schema=aus_census_2011 --format=c > /data-loader/tmp/ealgis-core
```

Extract aus_census_2011 schema:
```
pg_dump --username=postgres --dbname=postgres --schema=aus_census_2011 --format=c > /data-loader/tmp/aus_census_2011
```

Restore EALGIS core tables:
```
pg_restore --username=postgres --dbname=ealgis /data-loader/tmp/ealgis-core
```

Restore aus_census_2011 schema:
```
pg_restore --username=postgres --dbname=ealgis /data-loader/tmp/aus_census_2011
```

**Comment by keithamoss** [comment]
```
pg_restore --username=postgres --dbname=ealgis /data-loader/tmp/ealgis-core

pg_restore --username=postgres --dbname=ealgis --jobs=8 --schema=aus_census_2011 /data-loader/tmp/aus_census_2011

pg_restore --username=postgres --dbname=ealgis --jobs=8 --use-list=/data-loader/tmp/list-minimal.txt /data-loader/tmp/aus_census_2011
pg_restore --username=postgres --dbname=ealgis --jobs=8 --use-list=/data-loader/tmp/list-minimal-attribute-tables.txt /data-loader/tmp/aus_census_2011

VACUUM ANALYZE;
```

**Comment by keithamoss** [comment]
```
psql -d ealgis -U postgres -a -f /data-loader/data/ealgis-aus-census-2011-master/aus_census_2011_matviews_v02.sql
```
