### ISSUE TITLE
Map layer does not update after saving layer form

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#73]
React 15.5 is being installed if node_modules is wiped, rather than 15.4. That may be the issue.

**Comment by grahame** [comment]
Bug reproduced in @keithamoss's dev environment. Dropping to react 15.4 fixes some errors in the chrome console, but not the core issue.

**Comment by keithamoss** [comment]
To check:

- [ ] Create a new layer and then change its border size
- [ ] Edit an existing layer and add an expression
- [ ] Edit an existing layer and remove an expression
- [ ] Edit an existing layer and change its fill

**Comment by keithamoss** [comment]
@grahame OK, this should be good now. I've rebuilt both frontend and django containers and can get all of this working for me now.
