### ISSUE TITLE
Provide a means of displaying information about a column identifier

### ISSUE THREAD

**Issue by keithamoss** [ealgis/ealgis#84]
For users that are either:

- Expert users with knowledge of Census column identifiers (e.g. B117) who need to double check their recollection, and
- For non-expert users who have been given a formula to input who would like to understand what's going on.

This could take the form of:

- A simple column lookup tool that the user types a column identifier in to and returns what we know about it
- A more passive tool that takes the expression and filter, tokenises the strings, extracts the column identifiers, and displays a summary panel to the user with what we know about them.

**Comment by grahame** [comment]
We need to remember there are many other tabular data sources too, and not
make it too census specific.

I was wondering if we should change the way queries are written internally.

So we actually fully resolve the tokens (b3 etc) as the user enters the
query and store a JSON object representing the resolved query.

We're then Ok if another b3 is invented later.

**Comment by keithamoss** [comment]
Yup, nothing Census-specific :)

Good thought re representing the query as a JSON blob!

**Comment by grahame** [comment]
I think it could work really well, then we have a react widget which
understands that and marshalls to and from some UI representation. :-)

**Comment by keithamoss** [comment]
Yup ----> #86 :)

**Comment by keithamoss** [comment]
Column info lookup taken care of by 909d74ba446f84a2d9e3a7f312368e6480683ba1.

Other comments in this issue have moved to #88.
